In [1]:
# Import dependencies
import os
import pandas as pd
import numpy as np
import random
import zipfile
random.seed(1)

In [2]:
# Path to the ZIP folder
zip_folder_path = 'raw_data.zip'  # Update this to the actual ZIP folder path

# Open the ZIP file
with zipfile.ZipFile(zip_folder_path, 'r') as zip_ref:
    # List all files inside the ZIP folder
    file_list = zip_ref.namelist()
    print("Files in ZIP:", file_list)  # To verify the file names inside the ZIP
    
    # Specify the CSV file you want to read
    csv_file_name = 'brfss_2023.csv'  # Update with the exact file name
    
    # Read the CSV file directly from the ZIP
    with zip_ref.open(csv_file_name) as csv_file:
        brfss_2023_dataset = pd.read_csv(csv_file)

Files in ZIP: ['brfss_2023.csv']


In [3]:
# Check how many rows and columns in the dataset
brfss_2023_dataset.shape

(433323, 350)

In [4]:
# Check the data we loaded is in the correct format
pd.set_option('display.max_columns', 500)
brfss_2023_dataset.head()

_STATE  FMONTH        IDATE IMONTH   IDAY    IYEAR  DISPCODE  \
0     1.0     1.0  b'03012023'  b'03'  b'01'  b'2023'    1100.0   
1     1.0     1.0  b'01062023'  b'01'  b'06'  b'2023'    1100.0   
2     1.0     1.0  b'03082023'  b'03'  b'08'  b'2023'    1100.0   
3     1.0     1.0  b'03062023'  b'03'  b'06'  b'2023'    1100.0   
4     1.0     1.0  b'01062023'  b'01'  b'06'  b'2023'    1100.0   

           SEQNO          _PSU  CTELENM1  PVTRESD1  COLGHOUS  STATERE1  \
0  b'2023000001'  2.023000e+09       1.0       1.0       NaN       1.0   
1  b'2023000002'  2.023000e+09       1.0       1.0       NaN       1.0   
2  b'2023000003'  2.023000e+09       1.0       1.0       NaN       1.0   
3  b'2023000004'  2.023000e+09       1.0       1.0       NaN       1.0   
4  b'2023000005'  2.023000e+09       1.0       1.0       NaN       1.0   

   CELPHON1  LADULT1  NUMADULT  RESPSLC1  LANDSEX2  LNDSXBRT  SAFETIME  \
0       2.0      1.0       2.0       1.0       2.0       NaN       NaN   
1       2.0      1.0       1.0       NaN       2.0       NaN       NaN   
2       2.0      1.0       1.0       NaN       2.0       NaN       NaN   
3       2.0      1.0       2.0       1.0       2.0       NaN       NaN   
4       2.0      1.0       1.0       NaN       2.0       NaN       NaN   

   CTELNUM1  CELLFON5  CADULT1  CELLSEX2  CELSXBRT  PVTRESD3  CCLGHOUS  \
0       NaN       NaN      NaN       NaN       NaN       NaN       NaN   
1       NaN       NaN      NaN       NaN       NaN       NaN       NaN   
2       NaN       NaN      NaN       NaN       NaN       NaN       NaN   
3       NaN       NaN      NaN       NaN       NaN       NaN       NaN   
4       NaN       NaN      NaN       NaN       NaN       NaN       NaN   

   CSTATE1  LANDLINE  HHADULT  SEXVAR  GENHLTH  PHYSHLTH  MENTHLTH  POORHLTH  \
0      NaN       NaN      NaN     2.0      2.0      88.0      88.0       NaN   
1      NaN       NaN      NaN     2.0      2.0      88.0      88.0       NaN   
2      NaN       NaN      NaN     2.0      4.0       6.0       2.0       1.0   
3      NaN       NaN      NaN     2.0      2.0       2.0      88.0      88.0   
4      NaN       NaN      NaN     2.0      4.0      88.0      88.0       NaN   

   PRIMINS1  PERSDOC3  MEDCOST1  CHECKUP1  EXERANY2  EXRACT12  EXEROFT1  \
0       3.0       1.0       2.0       2.0       2.0       NaN       NaN   
1       3.0       1.0       2.0       2.0       1.0       1.0     106.0   
2       3.0       1.0       1.0       1.0       1.0       1.0     205.0   
3       3.0       1.0       2.0       3.0       1.0       1.0     103.0   
4       3.0       1.0       2.0       1.0       1.0       1.0     102.0   

   EXERHMM1  EXRACT22  EXEROFT2  EXERHMM2  STRENGTH  BPHIGH6  BPMEDS1  \
0       NaN       NaN       NaN       NaN     888.0      1.0      1.0   
1      30.0      88.0       NaN       NaN     888.0      1.0      2.0   
2      15.0      88.0       NaN       NaN     205.0      1.0      1.0   
3      30.0      88.0       NaN       NaN     888.0      3.0      NaN   
4      45.0       8.0     107.0     100.0     888.0      1.0      1.0   

   CHOLCHK3  TOLDHI3  CHOLMED3  CVDINFR4  CVDCRHD4  CVDSTRK3  ASTHMA3  \
0       3.0      2.0       2.0       2.0       2.0       2.0      2.0   
1       2.0      1.0       1.0       2.0       2.0       2.0      2.0   
2       2.0      1.0       1.0       2.0       2.0       2.0      1.0   
3       3.0      2.0       2.0       2.0       2.0       2.0      2.0   
4       2.0      2.0       2.0       2.0       2.0       2.0      2.0   

   ASTHNOW  CHCSCNC1  CHCOCNC1  CHCCOPD3  ADDEPEV3  CHCKDNY2  HAVARTH4  \
0      NaN       2.0       2.0       2.0       2.0       2.0       2.0   
1      NaN       2.0       2.0       2.0       1.0       2.0       1.0   
2      1.0       2.0       2.0       2.0       2.0       2.0       1.0   
3      NaN       1.0       1.0       2.0       1.0       2.0       1.0   
4      NaN       2.0       1.0       2.0       1.0       2.0       1.0   

   DIABETE

In [5]:
# Select specific columns
brfss_df_selected = brfss_2023_dataset[['DIABETE4',
                                         '_RFHYPE6',  
                                         'TOLDHI3', 'CHOLCHK3', 
                                         '_BMI5CAT',
                                         '_PACAT3',
                                         'CHECKUP1', 
                                         '_SMOKER3',
                                         'CHCKDNY2',
                                         'CVDSTRK3', '_MICHD', 
                                         '_TOTINDA', 
                                         '_RFDRHV8',
                                         'MARITAL',
                                         'EMPLOY1', 
                                         '_HLTHPL1', 'MEDCOST1', 
                                         'GENHLTH', 'MENTHLTH', 'PHYSHLTH', 'DIFFWALK', 
                                         '_SEX', '_AGEG5YR', 'EDUCA', 'INCOME3' ]]

In [6]:
# Check how many rows and columns after selection
brfss_df_selected.shape

(433323, 25)

In [7]:
# Preview the dataframe after selection
brfss_df_selected.head()

DIABETE4  _RFHYPE6  TOLDHI3  CHOLCHK3  _BMI5CAT  _PACAT3  CHECKUP1  \
0       1.0       2.0      2.0       3.0       4.0      4.0       2.0   
1       3.0       2.0      1.0       2.0       3.0      1.0       2.0   
2       3.0       2.0      1.0       2.0       2.0      9.0       1.0   
3       3.0       1.0      2.0       3.0       3.0      9.0       3.0   
4       1.0       2.0      2.0       2.0       3.0      1.0       1.0   

   _SMOKER3  CHCKDNY2  CVDSTRK3  _MICHD  _TOTINDA  _RFDRHV8  MARITAL  EMPLOY1  \
0       4.0       2.0       2.0     2.0       2.0       1.0      1.0      7.0   
1       4.0       2.0       2.0     2.0       1.0       1.0      2.0      7.0   
2       3.0       2.0       2.0     2.0       1.0       1.0      3.0      7.0   
3       4.0       2.0       2.0     2.0       1.0       1.0      1.0      7.0   
4       4.0       2.0       2.0     2.0       1.0       1.0      3.0      8.0   

   _HLTHPL1  MEDCOST1  GENHLTH  MENTHLTH  PHYSHLTH  DIFFWALK  _SEX  _AGEG5YR  \
0       1.0       2.0      2.0      88.0      88.0       1.0   2.0      13.0   
1       1.0       2.0      2.0      88.0      88.0       2.0   2.0      13.0   
2       1.0       1.0      4.0       2.0       6.0       1.0   2.0      13.0   
3       1.0       2.0      2.0      88.0       2.0       1.0   2.0      12.0   
4       1.0       2.0      4.0      88.0      88.0       1.0   2.0      12.0   

   EDUCA  INCOME3  
0    5.0     99.0  
1    5.0     99.0  
2    4.0      2.0  
3    5.0     99.0  
4    5.0      7.0

## Clean the data

In [8]:
#Drop missing values
brfss_df_selected = brfss_df_selected.dropna()
brfss_df_selected.shape

(341405, 25)

### Choosing 25 health indicators

In [9]:
# Reclassify DIABETE4 to match the new ordinal values:
# 0: No diabetes or only during pregnancy
# 1: Pre-diabetes or borderline diabetes
# 2: Yes diabetes

# Replace the values in DIABETE4 column
brfss_df_selected['DIABETE4'] = brfss_df_selected['DIABETE4'].replace({
    1: 2,  # Yes
    2: 0,  # Yes, but female told only during pregnancy
    3: 0,  # No
    4: 1,  # Pre-diabetes or borderline diabetes
})

# Remove rows with 'Don't know' (7) and 'Refused' (9)
brfss_df_selected = brfss_df_selected[~brfss_df_selected['DIABETE4'].isin([7, 9])]

# Verify the unique values in DIABETE4
print(brfss_df_selected['DIABETE4'].unique())

[2. 0. 1.]


In [10]:
#1 _RFHYPE6
#Change 1 to 0 so it represetnts No high blood pressure and 2 to 1 so it represents high blood pressure
brfss_df_selected['_RFHYPE6'] = brfss_df_selected['_RFHYPE6'].replace({1:0, 2:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected._RFHYPE6 != 9]
brfss_df_selected._RFHYPE6.unique()

array([1., 0.])

In [11]:
#2 TOLDHI3
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['TOLDHI3'] = brfss_df_selected['TOLDHI3'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.TOLDHI3 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.TOLDHI3 != 9]
brfss_df_selected.TOLDHI3.unique()

array([0., 1.])

In [12]:
#3 CHOLCHK3
brfss_df_selected.CHOLCHK3.unique()

array([3., 2., 4., 8., 6., 5.])

In [13]:
#4 _PACAT3
brfss_df_selected._PACAT3.unique()

array([4., 1., 9., 2., 3.])

In [14]:
#5 _SMOKER3
brfss_df_selected = brfss_df_selected[brfss_df_selected._SMOKER3 != 9]
brfss_df_selected._SMOKER3.unique()

array([4., 3., 1., 2.])

In [15]:
#6 CVDSTRK3
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['CVDSTRK3'] = brfss_df_selected['CVDSTRK3'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.CVDSTRK3 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.CVDSTRK3 != 9]
brfss_df_selected.CVDSTRK3.unique()

array([0., 1.])

In [16]:
#7 MARITAL
brfss_df_selected = brfss_df_selected[brfss_df_selected.MARITAL != 9]
brfss_df_selected._MICHD.unique()

array([2., 1.])

In [17]:
#8  CHECKUP1
brfss_df_selected = brfss_df_selected[brfss_df_selected.CHECKUP1 != 9]
brfss_df_selected._MICHD.unique()

array([2., 1.])

In [18]:
#9 _MICHD
#Change 2 to 0 because this means did not have MI or CHD
brfss_df_selected['_MICHD'] = brfss_df_selected['_MICHD'].replace({2: 0})
brfss_df_selected._MICHD.unique()

array([0., 1.])

In [19]:
#10  _TOTINDA
# 1 for physical activity
# change 2 to 0 for no physical activity
# Remove all 9 (don't know/refused)
brfss_df_selected['_TOTINDA'] = brfss_df_selected['_TOTINDA'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._TOTINDA != 9]
brfss_df_selected._TOTINDA.unique()

array([0., 1.])

In [20]:
#11 _RFDRHV8
# Change 1 to 0 (1 was no for heavy drinking). change all 2 to 1 (2 was yes for heavy drinking)
# remove all dont knows and missing 9
brfss_df_selected['_RFDRHV8'] = brfss_df_selected['_RFDRHV8'].replace({1:0, 2:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected._RFDRHV8 != 9]
brfss_df_selected._RFDRHV8.unique()

array([0., 1.])

In [21]:
#12 _HLTHPL1
# 1 is yes, change 2 to 0 because it is No health care access
# remove 7 and 9 for don't know or refused
brfss_df_selected['_HLTHPL1'] = brfss_df_selected['_HLTHPL1'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._HLTHPL1 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected._HLTHPL1 != 9]
brfss_df_selected._HLTHPL1.unique()

array([1., 0.])

In [22]:
#13 MEDCOST1
# Change 2 to 0 for no, 1 is already yes
# remove 7 for don/t know and 9 for refused
brfss_df_selected['MEDCOST1'] = brfss_df_selected['MEDCOST1'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.MEDCOST1 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.MEDCOST1 != 9]
brfss_df_selected.MEDCOST1.unique()

array([0., 1.])

In [23]:
#14 GENHLTH
# This is an ordinal variable that I want to keep (1 is Excellent -> 5 is Poor)
# Remove 7 and 9 for don't know and refused
brfss_df_selected = brfss_df_selected[brfss_df_selected.GENHLTH != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.GENHLTH != 9]
brfss_df_selected.GENHLTH.unique()

array([2., 4., 3., 1., 5.])

In [24]:
#15 MENTHLTH
# already in days so keep that, scale will be 0-30
# change 88 to 0 because it means none (no bad mental health days)
# remove 77 and 99 for don't know not sure and refused
brfss_df_selected['MENTHLTH'] = brfss_df_selected['MENTHLTH'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.MENTHLTH != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.MENTHLTH != 99]
brfss_df_selected.MENTHLTH.unique()

array([ 0.,  2.,  3., 25., 10., 30., 20., 15.,  5., 12.,  4.,  1.,  6.,
       21.,  7., 14., 29.,  8., 16., 17.,  9., 28., 11., 18., 22., 24.,
       13., 27., 26., 19., 23.])

In [25]:
#16 PHYSHLTH
# already in days so keep that, scale will be 0-30
# change 88 to 0 because it means none (no bad mental health days)
# remove 77 and 99 for don't know not sure and refused
brfss_df_selected['PHYSHLTH'] = brfss_df_selected['PHYSHLTH'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.PHYSHLTH != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.PHYSHLTH != 99]
brfss_df_selected.PHYSHLTH.unique()

array([ 0.,  6.,  2.,  1.,  5.,  4., 15., 30., 21., 10., 25.,  7., 20.,
        3., 12., 26., 14.,  8., 24., 18., 13., 28., 16., 17., 11., 22.,
       27.,  9., 29., 23., 19.])

In [26]:
#17 DIFFWALK
# change 2 to 0 for no. 1 is already yes
# remove 7 and 9 for don't know not sure and refused
brfss_df_selected['DIFFWALK'] = brfss_df_selected['DIFFWALK'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIFFWALK != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIFFWALK != 9]
brfss_df_selected.DIFFWALK.unique()

array([1., 0.])

In [27]:
#18 SEX
# in other words - is respondent male (somewhat arbitrarily chose this change because men are at higher risk for heart disease)
# change 2 to 0 (female as 0). Male is 1
brfss_df_selected['_SEX'] = brfss_df_selected['_SEX'].replace({2:0})
brfss_df_selected._SEX.unique()

array([0., 1.])

In [28]:
#19_AGEG5YR
# already ordinal. 1 is 18-24 all the way up to 13 wis 80 and older. 5 year increments.
# remove 14 because it is don't know or missing
brfss_df_selected = brfss_df_selected[brfss_df_selected._AGEG5YR != 14]
brfss_df_selected._AGEG5YR.unique()

array([13., 12.,  9.,  8., 10., 11.,  6.,  4.,  5.,  7.,  2.,  1.,  3.])

In [29]:
#20 EDUCA
# This is already an ordinal variable with 1 being never attended school or kindergarten only up to 6 being college 4 years or more
# Scale here is 1-6
# Remove 9 for refused:
brfss_df_selected = brfss_df_selected[brfss_df_selected.EDUCA != 9]
brfss_df_selected.EDUCA.unique()

array([5., 4., 6., 3., 2., 1.])

In [30]:
#21 INCOME3
# Variable is already ordinal with 1 being less than $10,000 all the way up to 8 being $75,000 or more
# Remove 77 and 99 for don't know and refused
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME3 != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME3 != 99]
brfss_df_selected.INCOME3.unique()

array([ 2.,  7.,  6.,  9.,  3.,  5.,  4.,  8., 11., 10.,  1.])

In [31]:
#22 EMPLOY1
brfss_df_selected = brfss_df_selected[brfss_df_selected.EMPLOY1 != 9]
brfss_df_selected.EMPLOY1.unique()

array([7., 8., 4., 5., 1., 2., 3., 6.])

In [32]:
#23 CHCKDNY2
brfss_df_selected = brfss_df_selected[brfss_df_selected.CHCKDNY2 != 9]
brfss_df_selected.CHCKDNY2.unique()

array([2., 1., 7.])

In [33]:
# Check Class Sizes of the target column DIABETE4
brfss_df_selected.groupby(['DIABETE4']).size()

DIABETE4
0.0    215320
1.0      6543
2.0     38012
dtype: int64

In [34]:
# Rename the columns to make them more readable
brfss = brfss_df_selected.rename(columns = {'DIABETE4':'Diabetes_012', 
                                         '_RFHYPE6':'HighBP',  
                                         'TOLDHI3':'HighChol', 'CHOLCHK3':'CholCheck', 
                                         '_BMI5CAT':'BMI', 
                                         '_SMOKER3':'Smoker', 
                                         'CVDSTRK3':'Stroke', '_MICHD':'HeartDiseaseorAttack', 
                                         '_TOTINDA':'LeisurePhysActivity',
                                         '_PACAT3': 'PhysActivity',
                                         'MARITAL': 'MaritalStatus',
                                         '_RFDRHV8':'HvyAlcoholConsump',
                                         'CHECKUP1': 'LastCheckup', 
                                         '_HLTHPL1':'AnyHealthcare', 'MEDCOST1':'NoDocbcCost', 
                                         'GENHLTH':'GenHlth', 'MENTHLTH':'MentHlth', 'PHYSHLTH':'PhysHlth', 'DIFFWALK':'DiffWalk', 
                                         '_SEX':'Sex', '_AGEG5YR':'Age', 'EDUCA':'Education', 'INCOME3':'Income' })



In [35]:
# Confirm all the columns were renamed successfully
brfss.head()

Diabetes_012  HighBP  HighChol  CholCheck  BMI  PhysActivity  LastCheckup  \
2           0.0     1.0       1.0        2.0  2.0           9.0          1.0   
4           2.0     1.0       0.0        2.0  3.0           1.0          1.0   
5           0.0     1.0       1.0        2.0  4.0           9.0          1.0   
8           0.0     1.0       1.0        2.0  4.0           4.0          1.0   
9           2.0     1.0       1.0        2.0  2.0           1.0          1.0   

   Smoker  CHCKDNY2  Stroke  HeartDiseaseorAttack  LeisurePhysActivity  \
2     3.0       2.0     0.0                   0.0                  1.0   
4     4.0       2.0     0.0                   0.0                  1.0   
5     4.0       2.0     0.0                   0.0                  1.0   
8     4.0       1.0     0.0                   0.0                  0.0   
9     3.0       2.0     0.0                   1.0                  1.0   

   HvyAlcoholConsump  MaritalStatus  EMPLOY1  AnyHealthcare  NoDocbcCost  \
2                0.0            3.0      7.0            1.0          1.0   
4                0.0            3.0      8.0            1.0          0.0   
5                0.0            3.0      7.0            1.0          0.0   
8                0.0            3.0      7.0            1.0          0.0   
9                0.0            1.0      7.0            1.0          0.0   

   GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  Income  
2      4.0       2.0       6.0       1.0  0.0  13.0        4.0     2.0  
4      4.0       0.0       0.0       1.0  0.0  12.0        5.0     7.0  
5      3.0       3.0       2.0       0.0  0.0   9.0        5.0     7.0  
8      3.0       0.0       5.0       1.0  0.0  13.0        5.0     6.0  
9      3.0       0.0       0.0       0.0  1.0  12.0        4.0     7.0

In [36]:
# Confirm (Number of Rows, Number of Columns)
brfss.shape

(259875, 25)

In [37]:
# Check how many respondents have no diabetes, prediabetes or diabetes. Note the class imbalance!
brfss.groupby(['Diabetes_012']).size()

Diabetes_012
0.0    215320
1.0      6543
2.0     38012
dtype: int64

### Save to csv
Save the first version where column DIABETE4 is the target variable. This is the full cleaned dataset with three classes: 0 (No diabetes), 1 (Pre-diabetes), and 2 (Diabetes).

In [ ]:
#************************************************************************************************
brfss.to_csv('Data/diabetes_012_health_indicators_BRFSS2023.csv', sep=",", index=False)
#************************************************************************************************

##  Creating a binary dataset: no diabetes vs. diabetes


In [39]:
# Make a copy of the cleaned dataframe
brfss_binary = brfss.copy()

# Reclassify the pre-diabetics instances from 1 to 0 and the diabetics instances from 2 to 1, so that 0 meaning non-diabetic and pre-diabetic and 1 meaning diabetic.
brfss_binary['Diabetes_012'] = brfss_binary['Diabetes_012'].replace({1:0})
brfss_binary['Diabetes_012'] = brfss_binary['Diabetes_012'].replace({2:1})

# Change the column name to Diabetes_binary
brfss_binary = brfss_binary.rename(columns = {'Diabetes_012': 'Diabetes_binary'})
brfss_binary.Diabetes_binary.unique()

array([0., 1.])

In [40]:
# Confirm the change on the column name
brfss_binary.head()

Diabetes_binary  HighBP  HighChol  CholCheck  BMI  PhysActivity  \
2              0.0     1.0       1.0        2.0  2.0           9.0   
4              1.0     1.0       0.0        2.0  3.0           1.0   
5              0.0     1.0       1.0        2.0  4.0           9.0   
8              0.0     1.0       1.0        2.0  4.0           4.0   
9              1.0     1.0       1.0        2.0  2.0           1.0   

   LastCheckup  Smoker  CHCKDNY2  Stroke  HeartDiseaseorAttack  \
2          1.0     3.0       2.0     0.0                   0.0   
4          1.0     4.0       2.0     0.0                   0.0   
5          1.0     4.0       2.0     0.0                   0.0   
8          1.0     4.0       1.0     0.0                   0.0   
9          1.0     3.0       2.0     0.0                   1.0   

   LeisurePhysActivity  HvyAlcoholConsump  MaritalStatus  EMPLOY1  \
2                  1.0                0.0            3.0      7.0   
4                  1.0                0.0            3.0      8.0   
5                  1.0                0.0            3.0      7.0   
8                  0.0                0.0            3.0      7.0   
9                  1.0                0.0            1.0      7.0   

   AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex  \
2            1.0          1.0      4.0       2.0       6.0       1.0  0.0   
4            1.0          0.0      4.0       0.0       0.0       1.0  0.0   
5            1.0          0.0      3.0       3.0       2.0       0.0  0.0   
8            1.0          0.0      3.0       0.0       5.0       1.0  0.0   
9            1.0          0.0      3.0       0.0       0.0       0.0  1.0   

    Age  Education  Income  
2  13.0        4.0     2.0  
4  12.0        5.0     7.0  
5   9.0        5.0     7.0  
8  13.0        5.0     6.0  
9  12.0        4.0     7.0

In [41]:
# Confirm the class reclassification was done successfully
brfss_binary.groupby(['Diabetes_binary']).size()

Diabetes_binary
0.0    221863
1.0     38012
dtype: int64

In [42]:
# Separate the 0 (Non-diabetes & Pre-diabetes) and 1 (Diabetes)
# Class 1 (diabetes group) dataframe
brfss_5050_1 = brfss_binary[brfss_binary['Diabetes_binary'] == 1]

# Class 0 (non-diabetes & pre-diabetes group) dataframe
brfss_5050_0 = brfss_binary[brfss_binary['Diabetes_binary'] == 0]

# Randomly select the same number of cases as the diabetes group from no-diabetes group (to balance classes)
num_diabetes_cases = len(brfss_5050_1)
brfss_5050_0_rand = brfss_5050_0.sample(n=num_diabetes_cases, random_state=42)

# Combine the two groups into one balanced DataFrame
brfss_5050 = pd.concat([brfss_5050_0_rand, brfss_5050_1], ignore_index=True)

# Verify the new balanced dataset
print(brfss_5050['Diabetes_binary'].value_counts())

Diabetes_binary
0.0    38012
1.0    38012
Name: count, dtype: int64


In [43]:
# Check the rows and columns of two dataframes: brfss_5050 and brfss_binary 
print(f'brfss_5050={brfss_5050.shape}',f'brfss_binary={brfss_binary.shape}')

brfss_5050=(76024, 25) brfss_binary=(259875, 25)


In [44]:
# Save the 50-50 balanced dataset to csv
#************************************************************************************************
brfss_5050.to_csv('Data/diabetes_binary_5050split_health_indicators_BRFSS2023.csv', sep=",", index=False)
#************************************************************************************************

# Also save the original binary dataset to csv
#************************************************************************************************
brfss_binary.to_csv('Data/diabetes_binary_health_indicators_BRFSS2023.csv', sep=",", index=False)
#************************************************************************************************